### ISSUE TITLE
PeerSniffer Class is missing

### ISSUE THREAD

**Issue by NorahNabil** [tambapps/P2P-File-Sharing#1]
Hello, 
appretiate the work and effort in this project. 
however I run it I noticed that PeerSniffer Class is not there therefore it throughs some errors. 

can you share that please. 
thank you

**Comment by tambapps** [comment]
Hello, thanks, sorry for the delay. Which project through some errors? the desktop app? android app? the library? the command_line?

You can find the PeerSniffer class in the p2p_library, here is the link: https://github.com/tambapps/P2P-File-Sharing/blob/master/p2p_library/src/main/kotlin/com/tambapps/p2p/fandem/sniff/PeerSniffer.kt
