### ISSUE TITLE
p2p_library erroneously shows transfer-compelted notification if connection was lost in the process

### ISSUE THREAD

**Issue by TheRDavid** [tambapps/P2P-File-Sharing#4]
Heya,
I am building an application on top of your peer-to-peer app on android and noticed that, if I disable wifi on my phone while it's looking for a connection, it displays the "Transfer completed" notification. 
I fixed it by going into 
`p2p_library/src/main/kotlin/com/tambapps/p2p/fandem/task/SendingTask.kt`

and adding
`super.cancel()`
in the catch-clause in `send()`:

```
@Throws(IOException::class)
  fun send(fis: InputStream?, fileName: String,
           fileSize: Long) {
    try {
      createServerSocket(fileName).use { serverSocket ->
        serverSocket.accept().use { socket ->
          transferListener?.onConnected(peer, Peer.of(socket), fileName, fileSize)
          CustomDataOutputStream(socket.getOutputStream()).use { dos ->
            dos.writeLong(fileSize)
            dos.writeInt(bufferSize)
            dos.writeString(fileName)
            share(bufferSize, fis!!, dos, fileSize)
          }
        }
      }
    } catch (e: SocketException) { //socket closed because of cancel()
      super.cancel() // this one right here
    }
  }
```

Not sure if that is a fix or more like a workaround though...

Either way, I'm gonna take the opportunity to say thank you for this project, it's extremely useful!

**Comment by tambapps** [comment]
Hello! thanks, that means a lot to me 

I think I will create a custom `TransferCancelException` extending IOException and then throw it here. This way, It will be easier to detect and handle a cancel from the sender side.

Thanks again for pointing out this bug

**Comment by tambapps** [comment]
This should now be fixed  by https://github.com/tambapps/P2P-File-Sharing/commit/a6f3f45b07f0e855b7464292e79d2e33343f0363

I also fixed it on the Android app, I should post a new realease next week
