### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by ngabomugisharobert** [tambapps/P2P-File-Sharing#7]
Hello,

There are some files that are missing in this project. File named "FileData" and "SendingFileData" that is supposed to be located in "model" package.

**Comment by tambapps** [comment]
Hello, sorry for the delay. They are in the model package, aren't they? Or maybe they weren't at the time you created this issue?

[SendingFileData](https://github.com/tambapps/P2P-File-Sharing/blob/master/p2p_library/src/main/java/com/tambapps/p2p/fandem/model/SendingFileData.java)

[FileData](https://github.com/tambapps/P2P-File-Sharing/blob/master/p2p_library/src/main/java/com/tambapps/p2p/fandem/model/FileData.java)

**Comment by tambapps** [comment]
Considering this problem as solved. Ping me if you still have issues about this
