### ISSUE TITLE
Failed to resolve: com.tambapps.p2p.fandem:fandem:3.1-SNAPSHOT

### ISSUE THREAD

**Issue by nikoladigi** [tambapps/P2P-File-Sharing#8]
Can not build the project, the lib is missing.

Thanks!

**Comment by tambapps** [comment]
Hello, what lib and project are you talking about?
To build any project (the desktop, command line, or android) you first have to install the `p2p_library` in your local maven registry. For that you'll need maven to run

```shell
cd p2p_library
mvn install
````

**Comment by tambapps** [comment]
Closing the issue for now. Re-open with more details about your problem if needed
